### ISSUE TITLE
will overwrite if save name

### ISSUE THREAD

**Issue by cbahai** [Innim/flutter_multiple_localization#4]
a.arb
{
  "abc": "yes!"
}

-------

b.arb
{
  "abc": "no!"
}

when use, "abc" aways "no!".

**Comment by greymag** [comment]
Hey!

That's not an issue - that's an expected behaviour. You can use it to override string value from package, as shown in [example](https://github.com/Innim/flutter_multiple_localization/blob/6ab4a79cf68855f3f663fc8dbea490e616b626ac/example/lib/main.dart#L38).

If you want to change a priority of the override than change order of delegates in `localizationsDelegates`:

```dart
MaterialApp(
  ...
  localizationsDelegates: [
    MaxPriorityLocalizations.delegate,
    LessPriorityLocalizations.delegate,
  ],
  ...
),
```
